# Generated by Django 3.0.3 on 2020-02-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='model_auto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='name_auto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='clearance',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='height',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='lenght',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.CharField(default='', max_length=15),
        ),
    ]
