# Generated by Django 3.0.3 on 2020-02-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20200216_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='weight',
            new_name='width',
        ),
    ]
